resources:
  repositories:
  # The name used to reference this repository in the checkout step
  - repository: BashCalcRepo 
    type: github
    endpoint: myGitHub
    name: sophie-norman/bashCalc
# The name used to reference this repository in the checkout step
  - repository: WindowsBatchRepo
    type: github
    endpoint: myGitHub
    name: sophie-norman/winBatch

trigger:
- master

stages:
  #First Stage on Ubuntu
  - stage: UbuntuQAEnvCheck
    jobs:
    - job: UbuntuQAInlineScripts

      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - checkout: none
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'

  - stage: UbuntuProdEnvCheck
    dependsOn: UbuntuQAEnvCheck
    condition: succeeded()
    jobs:
    - job: UbuntuProdExternalScripts
      pool:
        vmImage: 'ubuntu-latest'
      # these variables only available in ExternalScripts job
      variables:
        FIRST: 100
        SECOND: 20
        OPERATION: 4
      steps:
        - checkout: BashCalcRepo
        - task: Bash@3
          displayName: 'install bc'
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo 'installation starts'
              sudo apt-get install bc
              echo 'installation ends'
        - task: Bash@3
          displayName: 'run calc'
          inputs:
            filePath: 'calc.sh'

#Third Stage on Windows QA
  - stage: WindowsQAEnvCheck
    dependsOn: UbuntuQAEnvCheck
    condition: succeeded()
    jobs:
    - job: WindowQAInternalScripts
    #Windows Microsoft hosted image
      pool:
        vmImage: 'windows-latest'
      steps:
      - checkout: none
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - script: |
          echo Learning is fun, enquire below.
          echo See https://www.kavinschool.com/content/
        displayName: 'Run a multi-line script'

  - stage: WindowsProdEnvCheck
    dependsOn: 
    - UbuntuProdEnvCheck
    - WindowsQAEnvCheck
    condition: succeeded()
    jobs:
    - job: ExternalScripts
      pool:
        vmImage: 'windows-latest'
      steps:
      - checkout: WindowsBatchRepo
      - task: BatchScript@1
        inputs:
          filename: 'power.bat'
          arguments: '3 4'
      - task: BatchScript@1
        inputs:
          filename: 'calc.bat'
          arguments: '300 100'